import { Profile, Team, Activity, SportRule, Challenge } from '@/types';

export const DEFAULT_SPORT_RULES: SportRule[] = [
  { id: '1', activity_type: 'Run', display_name: 'Chạy bộ', multiplier: 1.0, bonus_per_100m_elevation: 0.5, icon: '🏃' },
  { id: '2', activity_type: 'Walk', display_name: 'Đi bộ', multiplier: 0.6, bonus_per_100m_elevation: 0.3, icon: '🚶' },
  { id: '3', activity_type: 'Hike', display_name: 'Leo núi', multiplier: 0.8, bonus_per_100m_elevation: 0.5, icon: '🥾' },
  { id: '4', activity_type: 'Ride', display_name: 'Đạp xe', multiplier: 0.3, bonus_per_100m_elevation: 0.2, icon: '🚴' },
  { id: '5', activity_type: 'Swim', display_name: 'Bơi lội', multiplier: 4.0, bonus_per_100m_elevation: 0.0, icon: '🏊' },
];

export const DEMO_TEAMS: Team[] = [
  {
    id: 'team-1',
    name: 'Cisco Cyber Runners ⚡',
    code: 'CYBER2026',
    avatar_url: 'https://images.unsplash.com/photo-1552674605-db6ffd4facb5?w=150&auto=format&fit=crop&q=80',
    description: 'Biệt đội An Ninh Mạng Cisco bứt phá cự ly!',
    member_count: 42,
    total_distance: 1420500,
    total_points: 1580.4,
    created_at: '2026-01-01',
  },
  {
    id: 'team-2',
    name: 'Cisco Cloud Velocity 🚀',
    code: 'CLOUD2026',
    avatar_url: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=150&auto=format&fit=crop&q=80',
    description: 'Chuyên gia Điện toán đám mây - Tốc độ dẫn đầu.',
    member_count: 35,
    total_distance: 1195000,
    total_points: 1340.2,
    created_at: '2026-01-05',
  },
  {
    id: 'team-3',
    name: 'Cisco Sales Strikers 🔥',
    code: 'SALES2026',
    avatar_url: 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=150&auto=format&fit=crop&q=80',
    description: 'Chinh phục mọi chỉ tiêu số và km dốc!',
    member_count: 48,
    total_distance: 1680000,
    total_points: 1720.8,
    created_at: '2026-01-10',
  },
  {
    id: 'team-4',
    name: 'Cisco Iron Ops 🦾',
    code: 'OPS2026',
    avatar_url: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=150&auto=format&fit=crop&q=80',
    description: 'Kỉ luật thép, dẻo dai và bền bỉ.',
    member_count: 38,
    total_distance: 980000,
    total_points: 1050.5,
    created_at: '2026-01-12',
  }
];

export const DEMO_PROFILES: Profile[] = [
  {
    id: 'usr-1',
    full_name: 'Nguyễn Văn Minh',
    email: 'minh.nguyen@cisco.com',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    department: 'Cybersecurity Architecture',
    role: 'admin',
    team_id: 'team-1',
    team: DEMO_TEAMS[0],
    strava_id: 998811,
    certificates: [
      {
        id: 'cert-1',
        title: '🏆 TOP 1 VẬN ĐỘNG VIÊN XUẤT SẮC TUẦN 38',
        type: 'weekly',
        recipient_name: 'Nguyễn Văn Minh',
        achievement_detail: 'Cự ly: 42.5 km • 45.2 pts quy đổi',
        issue_date: '19/09/2026',
        badge_color: 'from-amber-400 to-yellow-600',
        verified_by: 'Ban Tổ Chức Cisco GSC Vietnam',
      },
      {
        id: 'cert-2',
        title: '🏅 FINISHER THÁCH ĐẤU BỨT PHÁ 100KM THÁNG 9',
        type: 'monthly',
        recipient_name: 'Nguyễn Văn Minh',
        achievement_detail: 'Hoàn thành mốc 125 km Chạy bộ & Leo dốc',
        issue_date: '15/09/2026',
        badge_color: 'from-cyan-400 to-blue-600',
        verified_by: 'Cisco Health & Sports Committee',
      }
    ],
    created_at: '2026-01-01',
  },
  {
    id: 'usr-2',
    full_name: 'Trần Thị Thu Hà',
    email: 'ha.tran@cisco.com',
    avatar_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    department: 'Cloud Solutions',
    role: 'captain',
    team_id: 'team-2',
    team: DEMO_TEAMS[1],
    strava_id: 998812,
    created_at: '2026-01-02',
  },
  {
    id: 'usr-3',
    full_name: 'Lê Hoàng Nam',
    email: 'nam.le@cisco.com',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    department: 'Enterprise Sales',
    role: 'captain',
    team_id: 'team-3',
    team: DEMO_TEAMS[2],
    strava_id: 998813,
    created_at: '2026-01-03',
  },
  {
    id: 'usr-4',
    full_name: 'Phạm Đức Anh',
    email: 'anh.pham@cisco.com',
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    department: 'DevOps & Networking',
    role: 'member',
    team_id: 'team-1',
    team: DEMO_TEAMS[0],
    strava_id: 998814,
    created_at: '2026-01-04',
  },
  {
    id: 'usr-5',
    full_name: 'Đặng Ngọc Mai',
    email: 'mai.dang@cisco.com',
    avatar_url: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    department: 'People & Culture',
    role: 'member',
    team_id: 'team-4',
    team: DEMO_TEAMS[3],
    strava_id: 998815,
    created_at: '2026-01-05',
  },
  {
    id: 'usr-6',
    full_name: 'Vũ Thanh Tùng',
    email: 'tung.vu@cisco.com',
    avatar_url: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
    department: 'Partner Ecosystem',
    role: 'member',
    team_id: 'team-3',
    team: DEMO_TEAMS[2],
    strava_id: 998816,
    created_at: '2026-01-06',
  }
];

export const DEMO_ACTIVITIES: Activity[] = [
  {
    id: 'act-1',
    profile_id: 'usr-1',
    profile: DEMO_PROFILES[0],
    strava_activity_id: 101,
    name: '🌅 Chạy sáng Hồ Tây bứt phá cự ly',
    type: 'Run',
    distance: 12500,
    moving_time: 3900,
    elapsed_time: 4000,
    total_elevation_gain: 120,
    calculated_points: 13.1,
    start_date: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    created_at: new Date().toISOString(),
  },
  {
    id: 'act-2',
    profile_id: 'usr-2',
    profile: DEMO_PROFILES[1],
    strava_activity_id: 102,
    name: '🚴 Tour Đạp xe Cầu Nhật Tân - Sóc Sơn',
    type: 'Ride',
    distance: 45000,
    moving_time: 5400,
    elapsed_time: 6000,
    total_elevation_gain: 350,
    calculated_points: 15.25,
    start_date: new Date(Date.now() - 14 * 3600 * 1000).toISOString(),
    created_at: new Date().toISOString(),
  },
  {
    id: 'act-3',
    profile_id: 'usr-3',
    profile: DEMO_PROFILES[2],
    strava_activity_id: 103,
    name: '🏃 Tempo Run công viên Cầu Giấy',
    type: 'Run',
    distance: 15000,
    moving_time: 4320,
    elapsed_time: 4400,
    total_elevation_gain: 50,
    calculated_points: 15.25,
    start_date: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
    created_at: new Date().toISOString(),
  },
  {
    id: 'act-4',
    profile_id: 'usr-4',
    profile: DEMO_PROFILES[3],
    strava_activity_id: 104,
    name: '🏊 Bơi sải rèn luyện thể lực 2000m',
    type: 'Swim',
    distance: 2000,
    moving_time: 2400,
    elapsed_time: 2500,
    total_elevation_gain: 0,
    calculated_points: 8.0,
    start_date: new Date(Date.now() - 36 * 3600 * 1000).toISOString(),
    created_at: new Date().toISOString(),
  },
  {
    id: 'act-5',
    profile_id: 'usr-5',
    profile: DEMO_PROFILES[4],
    strava_activity_id: 105,
    name: '🚶 Đi bộ thư giãn buổi tối quanh công viên',
    type: 'Walk',
    distance: 6000,
    moving_time: 4200,
    elapsed_time: 4300,
    total_elevation_gain: 20,
    calculated_points: 3.7,
    start_date: new Date(Date.now() - 48 * 3600 * 1000).toISOString(),
    created_at: new Date().toISOString(),
  }
];

export const DEMO_CHALLENGES: Challenge[] = [
  {
    id: 'ch-1',
    title: '🏆 CISCO MARATHON THÁNG 10',
    description: 'Thách đấu chinh phục 100 km chạy bộ trong tháng 10 dành cho tất cả nhân viên Cisco.',
    type: 'Run',
    target_km: 100,
    start_date: '2026-10-01',
    end_date: '2026-10-31',
    banner_url: '/images/cisco_sports_hero.jpg',
    participant_ids: ['usr-1', 'usr-2', 'usr-3', 'usr-4', 'usr-5', 'usr-6'],
    status: 'active',
  },
  {
    id: 'ch-2',
    title: '🚴 TOUR DE CISCO CYCLING 300KM',
    description: 'Thách thức đạp xe đường dài tích lũy 300 km nâng cao sức bền tim mạch.',
    type: 'Ride',
    target_km: 300,
    start_date: '2026-10-05',
    end_date: '2026-11-05',
    banner_url: '/images/cisco_team_victory.jpg',
    participant_ids: ['usr-1', 'usr-2', 'usr-6'],
    status: 'active',
  },
  {
    id: 'ch-3',
    title: '🚶 CISCO HEALTH WALK 50KM',
    description: 'Đi bộ rèn luyện sức khỏe công sở dành cho đội nhóm Cisco.',
    type: 'Walk',
    target_km: 50,
    start_date: '2026-10-10',
    end_date: '2026-10-25',
    banner_url: '/images/cisco_sports_hero.jpg',
    participant_ids: ['usr-3', 'usr-4', 'usr-5'],
    status: 'upcoming',
  }
];
